### ISSUE TITLE
Can it run under Fabrice Bellard's JSLinux Emulator?

### ISSUE THREAD

**Issue by gek169** [ZenithOS/ZenithOS#6]
F. Bellard wrote an x86 (and compatibles...) emulator based on his other project Qemu.
It runs entirely in the browser.

Would it be possible to have a github.io page that hosts Zenith for people to use on the web, without having to install it natively?
More poignantly, could you get the audio working?

**Comment by TomAwezome** [comment]
JSLinux does not implement x86-64, so this is not possible. A similar online x86 virtualization tool exists called v86, but this also does not support 64-bit operating systems.
